### PR TITLE
Cleanup delete.go a bit

### PR DESCRIPTION
**Pull request by imikushin**
Add delete command and cleanup delete.go a bit

Delete dir if the package has subpackages and the dir is not in a declared subpackage. 
If a subpackage is (or ends with) '.', then it's subdirs won't be considered to be used.

### CODE REVIEW

**Comment by imikushin** [comment]
I needed to remove unused packages after `glide up`, because I vendor dependencies and want to have leaner checkouts, but didn't want to mess up with what people are used to.

Usage: `glide del`

**Comment by mattfarina** [comment]
@imikushin thanks for the pull request.

We're working on a change for locking/pinning (#143 for details) and this includes prune functionality. I'd like to hold off a few weeks on this until we get far along in that so the prune feature can be tied to that. The branch that work is happening on is quickly diverging from master. We're trying to keep master stable because so many people pull from that directly rather than a release.

That ok for you?

**Comment by imikushin** [comment]
@mattfarina I'm looking forward to #143 being implemented. 

I'll remove the `delete` command from this PR and will only leave the small fixes to `delete.go`. They are basically dealing with path prefixes:
e.g. `github.com/docker/docker` is a valid path prefix for `github.com/docker/docker/api`, but not for `github.com/docker/dockerinit`

I guess, I'll have to use my fork for a while to delete unused packages from vendor: we (@ Rancher Labs) have a policy to store the vendored libs under version control, so the prune feature is pretty much a requirement.

**Comment by technosophos** [comment]
This looks pretty straightforward to me. I don't understand why we'd need to loop over subpackages separately, though.

**Comment by mattfarina** [comment]
This PR is no longer compatible with the current state of the codebase. A PR against the current state of the codebase (there were major changes) is something we'd be happy to look at. Closing.

**Pull request closed without merging**
