### PR TITLE
 Instructions to install from PPA

### PR DESCRIPTION
**Pull request by franciscocpg**
Hello,

I am proposing this pull request to announce that I am publishing *glide* through PPA (https://launchpad.net/~masterminds/+archive/ubuntu/glide).

I created a team called masterminds (https://launchpad.net/~masterminds) at launchpad and I'd like to add @mattfarina as an admin member of this team (If he wants to, of course).

The project that automates this publishing is here (https://github.com/franciscocpg/glide-ppa) but is still *beta*. Once this project becomes stable I'd like to transfer its ownership to *Masterminds* (again, if there is some interest in doing so).

My next goal is publishing to [snappy](https://developer.ubuntu.com/en/snappy/) as this is going to replace deb packages in the future.

### CODE REVIEW

**Comment by mattfarina** [comment]
Note, the failed test was due to a bug in Glide fixed in #395.

**Comment by mattfarina** [comment]
@franciscocpg thanks for creating the PPA and loading Glide there. Before I merge, a couple things.

1. What was the plan for updates on new releases?
2. Can you add @technosophos ([technosophos](https://launchpad.net/~technosophos) on launchpad.net) and I ([mattfarina](https://launchpad.net/~mattfarina) on launchpad.net) to the [masterminds](https://launchpad.net/~masterminds) team. I'd just like to make sure more than one person can update for new releases.

I also need to run a couple tests to make sure the things are working.

**Comment by franciscocpg** [comment]
Hi @mattfarina 
1. Thats a good point. How are you guys doing with homebrew?
2. Done!

**Comment by mattfarina** [comment]
@franciscocpg when I create a new Glide release I also do a new homebrew release. It only takes a couple minutes.

Were you thinking of updating the ppa every time there is a glide release?

**Comment by mattfarina** [comment]
Also, the CI error here can be ignored. It's been fixed on master and I know what it is.

**Comment by franciscocpg** [comment]
@mattfarina, The homebrew release is a manual process?
Yes, I can update the ppa for every glide release.

**Comment by technosophos** [comment]
@franciscocpg This is awesome. Thanks!

**Comment by mattfarina** [comment]
@franciscocpg thanks. this has been merged.

**Pull request merged**
