### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yanyiwu**

### CODE REVIEW

**Comment by yanyiwu** [comment]
https://github.com/Masterminds/glide/issues/408

**Comment by mattfarina** [comment]
@yanyiwu the problem with this is it's telling people to install the tip of master rather than a [release version](https://en.wikipedia.org/wiki/Software_versioning). We don't ask people to install Go at the tip of master so why should we ask people to install Glide that way?

**Comment by yanyiwu** [comment]
To the most users, they meet this project at first time, they want to find the way to use it as easier as possible , when they can not find out, they will leave.

when i introduce this project to others, they alway complain installation is too sophisiticated. 

when we use codes in our project ,the version of codes is important, when we use a tool, for example,vim,brew or others, we dont care about their version as long as it can work.

**Comment by sdboyer** [comment]
> when we use a tool, for example,vim,brew or others, we dont care about their version as long as it can work.

Sorry, but this is a false comparison.

You might not care about what version of vim, brew, or others that you're using, but that's because you ARE getting stable versions of them - which is a guarantee provided by the design of the system you're using to get those packages. `

`go get` is *not* designed to get stable versions - just, whatever the latest `HEAD` is. Ironically, this is one of the arguments for having something like glide exist in the first place.

The best, most stable thing that could probably be done is providing a script that allows installation via something like `curl <URL> | sh`.

**Comment by mattfarina** [comment]
@yanyiwu You bring up a good point. Making it easier to install would be useful.

When you install brew, etc you get the latest release rather than the tip of development. That's my concern.

Today you can:
* Install via a binary
* Install with `brew install glide`
* Add an apt repo and install with `apt-get install glide` under ubuntu.

What do you think of the method brew and [helm](http://helm.sh/) provide with a script and a native windows method?

**Comment by franciscocpg** [comment]
I think that @sdboyer suggestion (`curl <URL> | sh`) is really a good option.
But for this to work we need to have releases for all supported platforms.
According to this [link](https://golang.org/src/go/build/build.go?s=#L260), here is the list of supported (cgo) platforms:
```
"darwin/386":      true,
"darwin/amd64":    true,
"darwin/arm":      true,
"darwin/arm64":    true,
"dragonfly/amd64": true,
"freebsd/386":     true,
"freebsd/amd64":   true,
"freebsd/arm":     true,
"linux/386":       true,
"linux/amd64":     true,
"linux/arm":       true,
"linux/arm64":     true,
"linux/ppc64le":   true,
"android/386":     true,
"android/amd64":   true,
"android/arm":     true,
"netbsd/386":      true,
"netbsd/amd64":    true,
"netbsd/arm":      true,
"openbsd/386":     true,
"openbsd/amd64":   true,
"solaris/amd64":   true,
"windows/386":     true,
"windows/amd64":   true,
```
@mattfarina: By the way, how are you doing the releases?

**Comment by mattfarina** [comment]
@franciscocpg releases are generated by running `make dist`. See https://github.com/Masterminds/glide/blob/master/Makefile#L30. It should be fairly easy to build distributions for other environments and create a shell script (for those crazy enough to run them).

**Comment by franciscocpg** [comment]
Ok @mattfarina 
I am going to start working on this.

**Comment by mattfarina** [comment]
I don't really want to advocate installing the latest dev snapshot as the primary method.

There is now a shell script that can install on *nix. It's in homebrew and we have a PPA.

Next steps are for binaries for more platforms (freebsd, arm, etc). There are other issues for that.

Would also be good to have a oneget install for Windows (e.g., `Install-Package glide`). But, I think that's for a future issue.

**Pull request closed without merging**
