### PR TITLE
Fixes incorrect build context when $GOROOT env var not set

### LINKED ISSUE #74: "glide guess" is broken with Go 1.5 official package installer
### Steps to reproduce

1. Remove previous Go version and any `$GOROOT` declarations in .bash_profile/.zshrc
2. Install go1.5.darwin-amd64.pkg from golang.org
3. Switch to any project folder within the `$GOPATH`
4. Run `glide create`
5. Run `glide guess`

### Expected result
`glide guess` does not fail

### Actual result
`glide guess` fails with error:

```sh
Oops! cannot find package "fmt" in any of:
	/usr/local/Cellar/go/1.5/libexec/src/fmt (from $GOROOT)
	/Users/Janek/go/src/fmt (from $GOPATH)
```

### Additional information

`/usr/local/Cellar` does not exist on my system. It seems to be the path were Go would be installed using `brew`.

`$GOROOT` env variable is **not** set on my system. This is not necessary with the package installer, since it installs Go to the default location used by the Go binary.

The Go binary correctly uses this location as its root path:

```sh
$ go env
(...)
GOPATH="/Users/Janek/go"
GOROOT="/usr/local/go"
```

It looks like `glide` always falls back to the path where `brew` installs Go. Obviously, when Go is not installed using `brew` this will break things.

**Proposed solution:**
Parse GOROOT from `go env` output.

### PR DESCRIPTION
**Pull request by janeczku**
Fixes #74 and #76

### CODE REVIEW

**Comment by technosophos** [comment]
I'm good with this. I am sorta in favor of removing the conditional and adding `buildContext` to the context so that any command that needs it can access it. `guess`, `tree`, and `list` definitely need it. I think `get` will likely need it in the near future.

**Comment by mattfarina** [comment]
@janeczku thanks for starting this.

I'd like to see a tweak to this. There are lots of times where `$GOROOT` isn't set and it's not required to be set. We can do something more intelligent.

Instead, it'd like to see a context builder as a utility function. It could be similar to the [`defaultContext`](https://github.com/golang/go/blob/go1.5.1/src/go/build/build.go#L287) function from the `go/build` package. Instead of getting the `$GOROOT` and other environment variables from the `runtime` package it could use the `go env [VAR]` command to get them (e.g., `go env GOROOT`). Or, if it's faster just parse the output of `go env` (without the variable name) to get the needed information.

The reason I suggest it as a utility function rather than on every run of Glide is because of the calls to the `go` program. Limit those to only the times it's needed. Essentially lazy load the information.

I filed golang/go#12567 to see if we can get easier access to the data. But, that wouldn't be for awhile and we can tackle this now.

**Comment by technosophos** [comment]
I was thinking about the utility function approach, too. It's slightly more consistent with what Go does, and what we've done elsewhere in our codebase. But the dependency injection style is the way we usually use Cookoo. In the present usage, though, I'm not sure we're gaining much by using DI.

I think that @mattfarina is right -- we should refactor this as a utility function to be called on demand.

**Comment by janeczku** [comment]
Great feedback! I might have done this as utility function in the first place, but i got distracted by what Cookoo had to offer :) I will refactor and then update this patch probably tomorrow.

**Comment by janeczku** [comment]
> Instead of getting the $GOROOT and other environment variables from the runtime package it could use the go env [VAR] command to get them (e.g., go env GOROOT). Or, if it's faster just parse the output of go env (without the variable name) to get the needed information.

It already does that :)

**Comment by mattfarina** [comment]
I'm reviewing now and testing some situations out (e.g., Windows)

**Comment by technosophos** [comment]
Huge thanks, @janeczku !

**Comment by janeczku** [comment]
Thanks back for this awesome tool! @technosophos @mattfarina

**Pull request merged**
