### PR TITLE
Allow relative imports using ../ to be ignored

### LINKED ISSUE #359: Ignores not working with relative imports
```
$ cd /tmp
$ git clone https://bitbucket.org/snippets/tmm1/krGBM glidetest

$ cd glidetest

$ ./bootstrap.sh
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/gin-gonic/gin.
[INFO] Resolving imports
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for /tmp/glidetest/one.
[WARN] Unable to checkout /tmp/glidetest/one
[ERROR] Update failed for /tmp/glidetest/one: Cannot detect VCS
[ERROR] Could not update packages: Cannot detect VCS
```

### PR DESCRIPTION
**Pull request by tmm1**
fixes #359

### CODE REVIEW

**Comment by technosophos** [comment]
I'm not sure I understand why this is a good idea. Wouldn't this simply break the cases for anyone who is using `../` inside of a proper GOPATH?

**Comment by tmm1** [comment]
Yea, you're right, this doesn't make much sense. I'm not even sure why it works, but I will dig further and update this PR with an isolated fix to the ignore logic.

**Comment by technosophos** [comment]
Okay. Ping me or drop into the Gitter room if you need to chat about it.

**Comment by tmm1** [comment]
With the latest change here, relative imports (starting with either `./` or `../`) are marked with a new `LocRelative`. This new type of import is ignored in the existing switch statements throughout the resolver, thereby ignoring relative imports and fixing all the issues I was having.

**Comment by mattfarina** [comment]
I think the `LocRelative` would need to be brought into the `glide tree` command as well.

@technosophos any thoughts on this implementation?

**Comment by mattfarina** [comment]
@tmm1 thanks for the contribution!

**Pull request merged**
