### PR TITLE
Track updated packages to avoid dup work

### LINKED ISSUE #308: fetches deps more than once
We have a dep ox X.  Something else we depend on has a dep on X, too.  When glide runs I get duplicate "Fetching updates for X".  One fix is to keep a map[string]bool that tracks updated packages.  To pass that through into both of the places that call VcsUpdate() is a little messy (ConcurrentUpdate() and InVendor() both call it).  As a hack, I added it to cfg.Config and plumbed it around.  It does seem to work but it's not the most clean.

Thoughts?

### PR DESCRIPTION
**Pull request by thockin**
Fixes #308 

I am not really happy with this, but I thought it was a better start to avoid passing around a whole additional argument to all the actions.  Better ideas welcome.

### CODE REVIEW

**Comment by technosophos** [comment]
Ah! Now I see what you were talking about in the issue. I had mentally confused VCS gets and dependency resolution. Really, there shouldn't be a case where a VcsGet operation is even requested twice, so there is some case in dependency resolution where we are not catching this case and it is trickling to the VcsGet layer. I'll be looking for that.

Thanks again!

@mattfarina I'd vote for putting this into 0.9.2 as well. It does clearly fix a bug that is clearly a performance issue.

**Comment by mattfarina** [comment]
I like where this is going but I don't like that this information was added to the config object. I'd like to avoid those becoming a junk drawer. I have a couple ideas to clean this up.

**Comment by thockin** [comment]
I had the same feeling, but it was that or literally pass a 2nd arg
everywhere conf was passed. Open to ideas. I am not attached to this, so
feel free to close and replace it if you get there before me.

**Comment by mattfarina** [comment]
@thockin I like what you started. I'm in the process of building on in.

**Comment by thockin** [comment]
Another alternative would be just to sleep a private may in vcs-management
code...

**Comment by mattfarina** [comment]
I'm going to close this because of #315 (which builds on this code). Details in that pull request.

**Pull request closed without merging**
