### PR TITLE
Fix 273

### PR DESCRIPTION
**Pull request by mattfarina**
Fixes the issue in #273.

### CODE REVIEW

**Comment by LK4D4** [comment]
@mattfarina 
```
Failed to build an initial list of packages to scan: no buildable Go source files in /home/moroz/project/workspace/src/github.com/docker/docker/profiles/seccomp
```
in docker :/

**Comment by mattfarina** [comment]
@LK4D4 You're right. Looking into that now.

**Comment by mattfarina** [comment]
@LK4D4 and @technosophos can you test this out?

**Comment by LK4D4** [comment]
@mattfarina Now I have old error:
```
Failed to build an initial list of packages to scan: found packages archive (archive.go) and main (example_changes.go)
```

**Comment by mattfarina** [comment]
@LK4D4 using the latest code on this pull request I can't reproduce the error. Can you give me an example?

**Comment by mattfarina** [comment]
Never mind, I figured out how to replicate it.

**Comment by mattfarina** [comment]
@LK4D4 This works for me to do both a `glide init` on Docker and import the archive package into another project.

**Comment by LK4D4** [comment]
@mattfarina seems like work now. There are new errors, but I think it's for another issue.

**Comment by mattfarina** [comment]
@LK4D4 Thanks. If you've got other issues I'm happy to poke at them.

**Comment by LK4D4** [comment]
@mattfarina I have four errors which unrelated to multiple packages:
```
[ERROR] Error scanning github.com/docker/distribution/reference: open /home/moroz/project/workspace/src/github.com/docker/docker/vendor/github.com/docker/distribution/reference: no such file
or directory
[ERROR] Error scanning github.com/docker/distribution/manifest/manifestlist: open /home/moroz/project/workspace/src/github.com/docker/docker/vendor/github.com/docker/distribution/manifest/manifestlist: no such file or directory
[ERROR] Error scanning github.com/docker/distribution/manifest/schema1: open /home/moroz/project/workspace/src/github.com/docker/docker/vendor/github.com/docker/distribution/manifest/schema1: no such file or directory
[ERROR] Error scanning github.com/docker/distribution/manifest/schema2: open /home/moroz/project/workspace/src/github.com/docker/docker/vendor/github.com/docker/distribution/manifest/schema2: no such file or directory
```
And so, there is no packages:
```
github.com/docker/distribution/manifest/manifestlist
github.com/docker/distribution/manifest/schema1
github.com/docker/distribution/manifest/schema2
github.com/docker/distribution/reference
```
They imported from `github.com/docker/docker/distribution` and `github.com/docker/docker/reference`. I don't see any tags or something tricky there, so it's better to look yourself.

**Pull request merged**
