### PR TITLE
Add a parameter to ignore subpackages check.

### PR DESCRIPTION
**Pull request by vburenin**
This is just a proposal that may help with fixing https://github.com/Masterminds/glide/issues/469

### CODE REVIEW

**Comment by itcreator** [comment]
+1

**Comment by franciscocpg** [comment]
I am getting the same error using an internal gitlab

**Comment by vburenin** [comment]
So I guess, we could merge this fix when I add tests, however, I do not like how I named the new parameter.

"nosubpackages" kinda conflicts with existing "subpackages". Any better proposition?

**Comment by sergeyklay** [comment]
+1

**Comment by vovanec** [comment]
+1

**Comment by vovanec** [comment]
ignore_subpackages?

**Comment by yulyt** [comment]
+1

**Comment by mattfarina** [comment]
First, thank you for putting some time into this. I appreciate the time put in and I appreciate that folks want this fixed.

A change to support package names that don't conform with `go get` should happen in name normalization. I would start inside [`util.NormalizeName`](https://github.com/Masterminds/glide/blob/f405e3789b5925d7282d4c2afab59a3827a688af/util/util.go#L306). If the regex lookup and go-get search don't find anything then handle this case.

**Pull request closed without merging**
