### PR TITLE
More detailed conflict information

### PR DESCRIPTION
**Pull request by mattfarina**

### CODE REVIEW

**Comment by mattfarina** [comment]
@technosophos @thockin this is work in progress but I'd be curious of your take on this type of information. For example,

```sh
[WARN] Conflict: github.com/aws/aws-sdk-go rev is currently bf2f8fe7f45e68017086d069498638893feddf64, but github.com/google/cadvisor wants 72440a9c5a884936f1c679591fcf04e31a9b772a
[INFO] github.com/aws/aws-sdk-go reference bf2f8fe7f45e68017086d069498638893feddf64:
[INFO] - author: Jason Del Ponte <delpontej@gmail.com>
[INFO] - commit date: Mon, 21 Dec 2015 11:30:48 -0800
[INFO] - subject (first line): Tag release v1.0.7
[INFO] github.com/aws/aws-sdk-go reference 72440a9c5a884936f1c679591fcf04e31a9b772a:
[INFO] - author: Jason Del Ponte <delpontej@gmail.com>
[INFO] - commit date: Tue, 16 Feb 2016 14:36:47 -0800
[INFO] - subject (first line): Tag release v1.1.3
[INFO] Keeping github.com/aws/aws-sdk-go bf2f8fe7f45e68017086d069498638893feddf64
```

This is still a work in progress. Looking for feedback before I continue.

**Comment by technosophos** [comment]
Wow. That's fabulous.

**Comment by sdboyer** [comment]
mmmmm, iiiinteresting. i like taking advantage of the VCS history to show information about the author of the conflicting change.

i *think* i should be on to working on conflict reporting in vsolver pretty soon...i'll have to make sure it's at least as good :)

**Comment by technosophos** [comment]
LGTM. Super excited to see this go in!

**Comment by thockin** [comment]
That looks...amazing.  Staggering.  OMG so helpful.

@vishh because we talked about some of this.

**Comment by mattfarina** [comment]
@technosophos @thockin As a next step I'd like to get smarter with commit ids. I think we can extract a tag if one is available and use that. So, if someone has a Godep file with a commit id we can extract the actual tag tied directly to that commit. If it's SemVer we can extract meaning or, at the very least, display the tag. See #353 for more details.

**Comment by vishh** [comment]
Woot

**Pull request merged**
