### PR TITLE
Fixed #578: Not resolving parent project packages in some cases

### LINKED ISSUE #578: Unable to create or update lock file for project when project directory is missing from cache
I'm seeing an issue trying to update dependencies for `github.com/decred/dcrd` when `glide update` is run from bitrig (an openbsd fork):

```
Script started on Wed Aug 24 12:08:23 2016
$ 
[0J$ pwd

/home/jrick/src/go/src/github.com/decred/dcrd
$ 
[0J$ glide --no-color update

[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching updates for github.com/btcsuite/btclog.
[INFO]  --> Fetching updates for github.com/btcsuite/fastsha256.
[INFO]  --> Fetching updates for github.com/btcsuite/websocket.
[INFO]  --> Fetching updates for github.com/btcsuite/go-socks.
[INFO]  --> Fetching updates for github.com/btcsuite/winsvc.
[INFO]  --> Fetching updates for github.com/btcsuite/seelog.
[INFO]  --> Fetching updates for github.com/btcsuite/goleveldb.
[INFO]  --> Fetching updates for github.com/btcsuite/golangcrypto.
[INFO]  --> Fetching updates for github.com/davecgh/go-spew.
[INFO]  --> Fetching updates for github.com/decred/bitset.
[INFO]  --> Fetching updates for github.com/decred/blake256.
[INFO]  --> Fetching updates for github.com/decred/dcrrpcclient.
[INFO]  --> Fetching updates for github.com/decred/dcrutil.
[INFO]  --> Fetching updates for github.com/decred/ed25519.
[INFO]  --> Fetching updates for golang.org/x/crypto.
[INFO]  --> Fetching updates for github.com/btcsuite/go-flags.
[INFO]  --> Setting version for github.com/btcsuite/seelog to v2.1.
[INFO]  Resolving imports
[ERROR] Error scanning github.com/decred/dcrd/chaincfg/chainhash: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/chaincfg/chainhash: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/wire: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/wire: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[INFO]  --> Fetching updates for github.com/btcsuite/snappy-go.
[ERROR] Error scanning github.com/decred/dcrd/chaincfg: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/chaincfg: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/chaincfg/chainec: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/chaincfg/chainec: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/blockchain: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/blockchain: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/txscript: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/txscript: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/dcrjson: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/dcrjson: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Failed to retrieve a list of dependencies: Error resolving imports
$ 
[0J$ exit


Script done on Wed Aug 24 12:09:29 2016
```

It also seems impossible to `update` even when an entirely new glide.yaml is created from `glide init`:

```
Script started on Wed Aug 24 12:15:33 2016
$ 
[0J$ rm glide.yaml glide.lock

$ 
[0J$ glide --no-color init

[INFO]  Generating a YAML configuration file and guessing the dependencies
[INFO]  Attempting to import from other package managers (use --skip-import to skip)
[INFO]  Scanning code to look for dependencies
[INFO]  --> Found reference to github.com/btcsuite/btclog
[INFO]  --> Found reference to github.com/btcsuite/fastsha256
[INFO]  --> Found reference to github.com/btcsuite/go-flags
[INFO]  --> Found reference to github.com/btcsuite/go-socks/socks
[INFO]  --> Found reference to github.com/btcsuite/golangcrypto/ripemd160
[INFO]  --> Found reference to github.com/btcsuite/goleveldb/leveldb
[INFO]  --> Adding sub-package leveldb/comparer to github.com/btcsuite/goleveldb
[INFO]  --> Adding sub-package leveldb/errors to github.com/btcsuite/goleveldb
[INFO]  --> Adding sub-package leveldb/filter to github.com/btcsuite/goleveldb
[INFO]  --> Adding sub-package leveldb/iterator to github.com/btcsuite/goleveldb
[INFO]  --> Adding sub-package leveldb/opt to github.com/btcsuite/goleveldb
[INFO]  --> Adding sub-package leveldb/util to github.com/btcsuite/goleveldb
[INFO]  --> Found reference to github.com/btcsuite/seelog
[INFO]  --> Found reference to github.com/btcsuite/websocket
[INFO]  --> Found reference to github.com/btcsuite/winsvc/eventlog
[INFO]  --> Adding sub-package mgr to github.com/btcsuite/winsvc
[INFO]  --> Adding sub-package svc to github.com/btcsuite/winsvc
[INFO]  --> Found reference to github.com/davecgh/go-spew/spew
[INFO]  --> Found reference to github.com/decred/bitset
[INFO]  --> Found reference to github.com/decred/blake256
[INFO]  --> Found reference to github.com/decred/dcrrpcclient
[INFO]  --> Found reference to github.com/decred/dcrutil
[INFO]  --> Adding sub-package bloom to github.com/decred/dcrutil
[INFO]  --> Found reference to github.com/decred/ed25519
[INFO]  --> Adding sub-package edwards25519 to github.com/decred/ed25519
[INFO]  --> Found reference to golang.org/x/crypto/ssh/terminal
[INFO]  --> Found test reference to github.com/stretchr/testify/assert
[INFO]  Writing configuration file (glide.yaml)
[INFO]  Would you like Glide to help you find ways to improve your glide.yaml configuration?
[INFO]  If you want to revisit this step you can use the config-wizard command at any time.
[INFO]  Yes (Y) or No (N)?
n
[INFO]  You can now edit the glide.yaml file. Consider:
[INFO]  --> Using versions and ranges. See https://glide.sh/docs/versions/
[INFO]  --> Adding additional metadata. See https://glide.sh/docs/glide.yaml/
[INFO]  --> Running the config-wizard command to improve the versions in your configuration
$ 
[0J$ glide --no-color update

[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching updates for github.com/btcsuite/go-flags.
[INFO]  --> Fetching updates for github.com/davecgh/go-spew.
[INFO]  --> Fetching updates for github.com/btcsuite/winsvc.
[INFO]  --> Fetching updates for github.com/decred/blake256.
[INFO]  --> Fetching updates for github.com/btcsuite/goleveldb.
[INFO]  --> Fetching updates for github.com/btcsuite/golangcrypto.
[INFO]  --> Fetching updates for github.com/btcsuite/go-socks.
[INFO]  --> Fetching updates for github.com/decred/bitset.
[INFO]  --> Fetching updates for github.com/btcsuite/seelog.
[INFO]  --> Fetching updates for github.com/btcsuite/websocket.
[INFO]  --> Fetching updates for github.com/decred/ed25519.
[INFO]  --> Fetching updates for github.com/decred/dcrrpcclient.
[INFO]  --> Fetching updates for github.com/btcsuite/fastsha256.
[INFO]  --> Fetching updates for github.com/btcsuite/btclog.
[INFO]  --> Fetching updates for github.com/decred/dcrutil.
[INFO]  --> Fetching updates for golang.org/x/crypto.
[INFO]  --> Fetching updates for github.com/stretchr/testify.
[INFO]  Resolving imports
[ERROR] Error scanning github.com/decred/dcrd/chaincfg/chainhash: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/chaincfg/chainhash: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/wire: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/wire: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[INFO]  --> Fetching updates for github.com/btcsuite/snappy-go.
[ERROR] Error scanning github.com/decred/dcrd/chaincfg: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/chaincfg: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/chaincfg/chainec: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/chaincfg/chainec: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/blockchain: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/blockchain: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/txscript: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/txscript: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning github.com/decred/dcrd/dcrjson: open /home/jrick/.glide/cache/src/https-github.com-decred-dcrd/dcrjson: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Failed to retrieve a list of dependencies: Error resolving imports
$ 
[0J$ exit


Script done on Wed Aug 24 12:16:13 2016
```

The same project can be successfully updated on Windows, and produces the following lockfile:

```
hash: 4648b5e89ce577ac30492bc77edc33a1176f4cbbb021495b1cb522c2588a5e90
updated: 2016-08-24T11:50:28.3908857-04:00
imports:
- name: github.com/btcsuite/btclog
  version: 73889fb79bd687870312b6e40effcecffbd57d30
- name: github.com/btcsuite/fastsha256
  version: 637e656429416087660c84436a2a035d69d54e2e
- name: github.com/btcsuite/go-flags
  version: 6c288d648c1cc1befcb90cb5511dcacf64ae8e61
- name: github.com/btcsuite/go-socks
  version: cfe8b59e565c1a5bd4e2005d77cd9aa8b2e14524
  subpackages:
  - socks
- name: github.com/btcsuite/golangcrypto
  version: 53f62d9b43e87a6c56975cf862af7edf33a8d0df
  subpackages:
  - ripemd160
- name: github.com/btcsuite/goleveldb
  version: 7834afc9e8cd15233b6c3d97e12674a31ca24602
  subpackages:
  - leveldb
  - leveldb/cache
  - leveldb/comparer
  - leveldb/errors
  - leveldb/filter
  - leveldb/iterator
  - leveldb/journal
  - leveldb/memdb
  - leveldb/opt
  - leveldb/storage
  - leveldb/table
  - leveldb/util
- name: github.com/btcsuite/seelog
  version: ae8891d029dd3c269dcfd6f261ad23e761acd99f
- name: github.com/btcsuite/snappy-go
  version: 0bdef8d067237991ddaa1bb6072a740bc40601ba
- name: github.com/btcsuite/websocket
  version: 31079b6807923eb23992c421b114992b95131b55
- name: github.com/btcsuite/winsvc
  version: f8fb11f83f7e860e3769a08e6811d1b399a43722
  subpackages:
  - eventlog
  - mgr
  - registry
  - svc
  - winapi
- name: github.com/davecgh/go-spew
  version: 6cf5744a041a0022271cefed95ba843f6d87fd51
  subpackages:
  - spew
- name: github.com/decred/bitset
  version: 484b833245d5f9046e2893a6bd2e54b1df3a53a4
- name: github.com/decred/blake256
  version: a840e32d7c31fe2e0218607334cb120a683951a4
- name: github.com/decred/dcrd
  version: 1c9d038acd64494435abe59fc5a2b136c1793354
  subpackages:
  - addrmgr
  - blockchain
  - blockchain/dbnamespace
  - blockchain/indexers
  - blockchain/stake
  - chaincfg
  - chaincfg/chainec
  - chaincfg/chainhash
  - database
  - database/ffldb
  - database/internal/treap
  - dcrec/edwards
  - dcrec/secp256k1
  - dcrec/secp256k1/schnorr
  - dcrjson
  - limits
  - mining
  - peer
  - txscript
  - wire
- name: github.com/decred/dcrrpcclient
  version: 103ed11be3a7035554d3925fbfaa67742641510f
- name: github.com/decred/dcrutil
  version: 4fc91a08eea88e74539d42d6301fd298b9bd8230
  subpackages:
  - base58
  - bloom
- name: github.com/decred/ed25519
  version: b0909d3f798b97a03c9e77023f97a5301a2a7900
  subpackages:
  - edwards25519
- name: golang.org/x/crypto
  version: 986d3313588aa5c68f1df95eac956f79cf3b2c01
  subpackages:
  - ssh/terminal
testImports:
- name: github.com/pmezard/go-difflib
  version: 792786c7400a136282c1664665ae0a8db921c6c2
  subpackages:
  - difflib
- name: github.com/stretchr/testify
  version: d77da356e56a7428ad25149ca77381849a6a5232
  subpackages:
  - assert
```

(Sidenote: Why did it list the project itself in the lockfile?)

I've gone through all dependencies in the vendor directory on Windows where the update succeeded, and did not find any other projects that included a glide.yaml, so those error messages about unsatisified version requirements don't make much sense in this case.

### PR DESCRIPTION
**Pull request by mattfarina**

### CODE REVIEW

**Comment by jrick** [comment]
Can confirm this fixes the issue with being unable to update.  The newly created glide.lock no longer has references to the project itself.  However I do see that it still vendored the project `github.com/decred/dcrd` into its own vendor directory.  Might be due to an A -> B -> A dependency on another of our repos.

**Comment by kujenga** [comment]
This fixes the issue with being unable to update for me as well 👍 

I'm also still seeing the package appearing within both my `vendor/` directory and the `glide.yaml` file though after running `glide up`.

**Comment by jrick** [comment]
Oops yes, i'm an idiot.  Was looking at glide.yaml not glide.lock.  The lockfile does still reference the project itself.

**Comment by mattfarina** [comment]
@jrick and @kujenga I think this latest commit fixes the problem. I tested it on `github.com/decred/dcrd` and it appears to fix the problem. Please let me know if you still see the issue.

**Comment by jrick** [comment]
Looks good!

**Comment by ApsOps** [comment]
Does this also fix #525 ?

**Comment by mattfarina** [comment]
@ApsOps I'm not sure. I'll need to look. I've not had a chance to figure out the root of the gin issue, yet.

**Comment by kujenga** [comment]
Works perfectly, thanks so much for the quick turnaround!

**Pull request merged**
