### PR TITLE
Fix error: Unable to export dependencies to vendor directory: Error m…

### PR DESCRIPTION
**Pull request by Ticore**
…oving files: exit status 1. output: Access is denied. 0 dir(s) moved.

### CODE REVIEW

**Comment by Ticore** [comment]
#873

**Comment by Vrakfall** [comment]
Solved #873 on my end (Windows 7, no UAC but I use Comodo's HIPS instead and it didn't trigger).
Although it feels like copying many files one by one, dunno the original behaviour.

**Comment by nilyang** [comment]
I have been solved this problem some days age and waiting for the PR #970 to merge to the master. 

You can also see the problem #960

**Comment by prdas31** [comment]
@AndrewLader 

That's great to know! 
But from where to install the 0.12.3 version and how?
Thanks.

**Comment by wuyanxin** [comment]
@prdas31  https://github.com/Masterminds/glide/releases

**Pull request closed without merging**
